---
version: 1

kind: group

hptuning:
  concurrency: 40
  bo:
    n_iterations: 15
    n_initial_trials: 40
    metric:
      name: loss
      optimization: minimize
    utility_function:
      n_warmup: 5
      n_iter: 10
      acquisition_function: ucb
      kappa: 2.576
      gaussian_process:
        kernel: matern
        length_scale: 1.0
        nu: 1.9
        n_restarts_optimizer: 0

  matrix:
    learning_rate:
      uniform: [0.001, 0.01]
    dropout:
      values: [0.2, 0.22, 0.25, 0.3, 0.35]
    activation:
      values: [relu, sigmoid]

declarations:
  batch_size: 128
  num_steps: 300
  num_epochs: 1

build:
  image: tensorflow/tensorflow:1.4.1-py3
  build_steps:
    - pip3 install --no-cache-dir -U polyaxon-client==0.4.2

run:
  cmd:  python3 model.py --batch_size={{ batch_size }} \
                         --num_steps={{ num_steps }} \
                         --learning_rate={{ learning_rate }} \
                         --dropout={{ dropout }} \
                         --num_epochs={{ num_epochs }} \
                         --activation={{ activation }}
